// <auto-generated />
namespace ExpenseWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TokenTableAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TokenTableAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202409241121132_Token-Table-Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
